/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About/index.vue')['default']
    Banner: typeof import('./src/components/Content/components/Banner.vue')['default']
    Clients: typeof import('./src/components/Pages/Clients/index.vue')['default']
    Compare: typeof import('./src/components/Compare/index.vue')['default']
    Contact: typeof import('./src/components/Contact/index.vue')['default']
    Content: typeof import('./src/components/Content/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Floor: typeof import('./src/components/Floor/index.vue')['default']
    Home: typeof import('./src/components/Home/index.vue')['default']
    LoginModel: typeof import('./src/components/Settings/components/LoginModel.vue')['default']
    Model_Library: typeof import('./src/components/Model_Library/index.vue')['default']
    Nav: typeof import('./src/components/Nav/index.vue')['default']
    Partake: typeof import('./src/components/Partake/index.vue')['default']
    Pricing: typeof import('./src/components/Pricing/index.vue')['default']
    Reviews: typeof import('./src/components/Pages/Reviews/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Service: typeof import('./src/components/Service/index.vue')['default']
    Settings: typeof import('./src/components/Settings/index.vue')['default']
    SinglePage: typeof import('./src/components/Pages/SinglePage/index.vue')['default']
    Skills: typeof import('./src/components/Pages/Skills/index.vue')['default']
    TeamMembers: typeof import('./src/components/Pages/TeamMembers/index.vue')['default']
    Wrong: typeof import('./src/components/Wrong/index.vue')['default']
  }
}
